### ISSUE TITLE
User id is not parsed from message tags

### ISSUE THREAD

**Issue by michaelforrest** [lexonegit/Unity-Twitch-Chat#2]
I spent a lot of time trying to find a Twitch API to find out a user's id from their chat nickname to no avail. Now, as I was converting aspects of this project to Swift, I discovered that this information is available in the tags stream. It would be really useful to be able to access this (next time I'm back in Unity, that is!)

**Raw example tags with user-id in bold:**
@badge-info=subscriber/17;badges=broadcaster/1,subscriber/0,premium/1;client-nonce=0f8d3e0f823c2933c949d1c64c11d979;color=#B8005C;display-name=MichaelForrest;emote-only=1;emotes=305612595:0-14;flags=;id=dbd0c90a-2b74-4de7-a7d1-64256fe8e984;mod=0;room-id=75620578;subscriber=1;tmi-sent-ts=1623257914746;turbo=0;**user-id=75620578**;user-type=

**Comment by lexonegit** [comment]
Hey @michaelforrest I've just updated the project. It now parses both user ID and channel ID. (room-id)

**Comment by michaelforrest** [comment]
Thanks @lexonegit, that's great. The only thing I'd say is it would be nice if this graphic was also updated :-)

![The nice graphic](https://camo.githubusercontent.com/6cbee6a560f820b091fb13fbe0151cf86ca8977623e12b3a38dd63063da67456/68747470733a2f2f692e696d6775722e636f6d2f4b4941384b635a2e706e67)
