### ISSUE TITLE
Start function when being followed or subbed

### ISSUE THREAD

**Issue by dariolaplaca** [lexonegit/Unity-Twitch-Chat#6]
Sorry I don't know if it's the right place to ask about this. There is a way to start a function upon being followed or after getting a sub?

**Comment by lexonegit** [comment]
Only normal chat messages are implemented. You might want to look at other Twitch IRC implementations such as https://github.com/TwitchLib/TwitchLib.Unity 

I haven't used it but looks like they support follow/subscriber alerts.
